import GithubSlugger from "github-slugger";

export type TocEntry = {
  /** 2 for h2, 3 for h3. */
  depth: 2 | 3;
  /** Plain-text heading content. */
  text: string;
  /** Slug id matching what `rehype-slug` will assign to the rendered heading. */
  id: string;
};

const HEADING_RE = /^(#{2,3})\s+(.+?)\s*$/gm;

/**
 * Extract a flat list of h2/h3 headings from raw MDX source. Code-fenced and
 * inline-code blocks are stripped first so a `## not a heading` inside a code
 * sample doesn't sneak in. Slug ids are generated by GithubSlugger so they
 * match what `rehype-slug` produces at render time.
 */
export function extractToc(source: string): TocEntry[] {
  const stripped = source
    .replace(/```[\s\S]*?```/g, "")
    .replace(/`[^`\n]+`/g, "");
  const slugger = new GithubSlugger();
  const out: TocEntry[] = [];
  for (const match of stripped.matchAll(HEADING_RE)) {
    const depth = match[1].length === 2 ? 2 : 3;
    const text = match[2].replace(/[*_`]/g, "").trim();
    if (!text) continue;
    out.push({ depth, text, id: slugger.slug(text) });
  }
  return out;
}
